export const PAGE_IDS = [
  "playground",
  "s1",
  "s2",
  "s3-bptree",
  "viz-bptree",
  "s3-hash",
  "s3-adv",
  "s4",
  "s5",
  "s6",
  "s8-ir",
  "s8-examen",
  "s8-viz",
  "s9-ir",
  "s9-examen",
  "s9",
  "s10-vec",
  "s10-examen",
  "s10-viz",
  "s11-eff",
  "s11-examen",
  "s12-bdd",
  "s12-examen",
  "s13-vert",
  "s13-examen",
  "s14-nosql",
  "s14-examen",
  "s15-nosql",
  "s15-examen",
  "viz-slotted",
  "viz-costs",
  "util-sintaxis",
  "util-fd",
  "util-norm",
  "util-examenes",
  "util-cheatsheet",
  "util-tools",
] as const;

export type PageId = (typeof PAGE_IDS)[number];

export const PAGE_TITLES: Record<PageId, string> = {
  playground: "SQL Playground",
  s1: "Arquitectura DBMS",
  s2: "Organización física y almacenamiento",
  "s3-bptree": "Técnicas de indexación",
  "viz-bptree": "Visualizador B+Tree",
  "s3-hash": "Hash Index",
  "s3-adv": "GIN, GiST, SP-GiST y BRIN",
  s4: "Algoritmos externos",
  s5: "Concurrencia y recuperación",
  s6: "Bases de datos espaciales",
  "s8-ir": "Recuperación de información textual",
  "s8-examen": "Examen: recuperación textual",
  "s8-viz": "Visualizador TF-IDF y coseno",
  "s9-ir": "Índice invertido optimizado",
  "s9-examen": "Examen: índices invertidos",
  s9: "OLAP y Data Warehousing",
  "s10-vec": "Bases de datos vectoriales",
  "s10-examen": "Examen: bases vectoriales",
  "s10-viz": "Visualizador k-NN y distancias",
  "s11-eff": "Búsqueda eficiente",
  "s11-examen": "Examen: búsqueda eficiente",
  "s12-bdd": "Bases de datos distribuidas",
  "s12-examen": "Examen: bases distribuidas",
  "s13-vert": "Fragmentación vertical",
  "s13-examen": "Examen: fragmentación vertical",
  "s14-nosql": "NoSQL y MongoDB",
  "s14-examen": "Examen: NoSQL y MongoDB",
  "s15-nosql": "Cassandra y Redis",
  "s15-examen": "Examen: Cassandra y Redis",
  "viz-slotted": "Visualizador de slotted pages",
  "viz-costs": "Comparador de costos de acceso",
  "util-sintaxis": "Sintaxis SQL",
  "util-fd": "Dependencias funcionales",
  "util-norm": "Normalización",
  "util-examenes": "Exámenes pasados",
  "util-cheatsheet": "SQL Cheat Sheet",
  "util-tools": "Herramientas",
};

const VALID_PAGE_IDS = new Set<string>(PAGE_IDS);

export function isPageId(value: string): value is PageId {
  return VALID_PAGE_IDS.has(value);
}
